name: somesweep
method: bayes
run_cap: 10
metric:
  name: val_loss
  goal: minimize
early_terminate:
  type: hyperband
  min_iter: 3
  eta: 3
parameters:
  lr: 
    values: [0.001, 0.0001]
  num_layers:
    distribution: int_uniform
    min: 1
    max: 2
  max_epochs:
    value: 2
  accelerator: 
    value: gpu