name: somerun
parameters:
  trainer:
    accelerator: cpu
    max_epochs: 10

  callback:
    name: { value: "default"}

  model:
    name: "random"
    lr: 0.001
    num_layers: 2

  datamodule:
    name: { value: "default"}
    batch_size: 32
    val_split: 0.2
    test_split: 0.1
  
    dataset: {}